# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


[double]$x = 1
[double]$y = 2
[double]$sum = 2
[double]$z
[double]$mod
do {

$z = $x + $y
$mod = $z % 2
if ($mod -eq 0) { $sum = $sum + $z }

Write-Host "Z =" $z
$x = $y
$y = $z

}
until ($z -ge 4000000)

Write-Host "Sum = " $sum 
