# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


[double]$x = 1
[double]$y = 2
[double]$sum = 2
[double]$z
for ($i=1; $i -le 4000000; $i++) 
{
    
    $z = $x + $y
    #Write-Host "X: $x"
    #Write-Host "Y: $y"
    #Write-Host "Z: $Z"
    
    if ($z/2 -is [double]) { $sum+=$z }
    
    $x = $y
    $y = $z
    #Write-Host "Sum: $sum"
    #Write-Host ""

}

$sum
